---
driver:
  name: vagrant
  customize:
    memory: 2048

provisioner:
  name: chef_zero
  environments_path: test/environments
  data_bags_path: test/data_bags

platforms:
  - name: ubuntu-14.04

suites:
  - name: production
    provisioner:
      client_rb:
        environment: certs-prod
    run_list:
      - recipe[chef_certificates::default]
    attributes:
      mysql:
        host: <%= `ipconfig getifaddr en0` %>
        password: certificates
      deployment:
        revision: baf0f799eb53ebf8a4a5d69d7ce47db5126bdc62
    
  - name: staging
    provisioner:
      client_rb:
        environment: certs-prod
    run_list:
      - recipe[chef_certificates::default]
    attributes:
      mysql:
        host: <%= `ipconfig getifaddr en0` %>
        password: certificates
      deployment:
        revision: STAGING
        nginx:
          prefix: staging
