---
driver:
  name: docker

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[british_values::default]
    attributes:
      ruby-ng:
        ruby_version: 1.9.3
        dev_package: 1.9.1
      user: 'certificates'
      repo: 'theodi/open-data-certificate'
      mysql:
        host: 10.14.1.111
        database: certificates
        password: certificates
