---
driver:
#  name: vagrant
  name: docker

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    data_bags_path: test/data_bags
    run_list:
      - recipe[british_values::default]
    attributes:
      envbuilder:
        base_dir: "/home/certificates"
        base_dbi: "production"
        owner: "certificates"
        group: "certificates"
      ruby-ng:
        ruby_version: 1.9.3
        dev_package: 1.9.1
      user: certificates
      fully_qualified_domain_name: certificates.theodi.org
      port: 8000
      repo: theodi/open-data-certificate
      mysql:
        host: <%= `ipconfig getifaddr en0` %>
        database: certificates
        password: certificates
      migrate: bundle exec rake db:schema:load
      deployment:
        revision: afc3334d1b16a2355b27b4afc56ece2efa221a3f
        rack_env: production
