---
driver:
  name: docker

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[british_values::default]
    attributes:
      ruby-ng:
        ruby_version: 1.9.3
      user: 'certificates'
