---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    data_bags_path: test/data_bags
    run_list:
      - recipe[chef_certificates::default]
    attributes:
      mysql:
        host: <%= `ipconfig getifaddr en0` %>
        password: certificates
      deployment:
        revision: baf0f799eb53ebf8a4a5d69d7ce47db5126bdc62

  - name: staging
    data_bags_path: test/data_bags
    run_list:
      - recipe[chef_certificates::default]
    attributes:
      mysql:
        host: <%= `ipconfig getifaddr en0` %>
        password: certificates
      deployment:
        revision: baf0f799eb53ebf8a4a5d69d7ce47db5126bdc62
        nginx:
          prefix: staging
