---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[arsebees::default]
    attributes:
      ruby-ng:
        ruby_version: 1.9.3
